- op: add
  path: /metadata/labels/llm-d.ai~1role
  value: decode
- op: add
  path: /spec/leaderWorkerTemplate/workerTemplate/metadata/labels/llm-d.ai~1role
  value: decode
- op: add
  path: /spec/leaderWorkerTemplate/size
  value: 2
- op: add
  path: /spec/leaderWorkerTemplate/workerTemplate/spec/initContainers
  value:
    - name: routing-proxy
      args:
        - --port=8000
        - --vllm-port=8200
        - --connector=nixlv2
        - -v=5
        - --secure-proxy=false
      image: ghcr.io/llm-d/llm-d-routing-sidecar:v0.2.0
      imagePullPolicy: Always
      ports:
        - containerPort: 8000
      resources: {}
      restartPolicy: Always
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
- op: add
  path: /spec/leaderWorkerTemplate/workerTemplate/spec/containers/0/command
  value:
    - /bin/bash
    - -c
- op: add
  path: /spec/leaderWorkerTemplate/workerTemplate/spec/containers/0/args
  value:
    - |-
      #################
      # RUN vLLM decode worker
      #################
      START_RANK=$(( ${LWS_WORKER_INDEX:-0} * DP_SIZE_LOCAL ))

      source /opt/vllm/bin/activate
      exec vllm serve \
        deepseek-ai/DeepSeek-R1-0528 \
        --port 8200 \
        --disable-log-requests \
        --disable-uvicorn-access-log \
        --enable-expert-parallel \
        --data-parallel-hybrid-lb \
        --tensor-parallel-size $TP_SIZE \
        --data-parallel-size $((LWS_GROUP_SIZE * DP_SIZE_LOCAL)) \
        --data-parallel-size-local $DP_SIZE_LOCAL \
        --data-parallel-address ${LWS_LEADER_ADDRESS} \
        --data-parallel-rpc-port 5555 \
        --data-parallel-start-rank $START_RANK \
        --trust-remote-code \
        --kv_transfer_config '{"kv_connector":"NixlConnector","kv_role":"kv_both"}'
- op: add
  path: /spec/leaderWorkerTemplate/workerTemplate/spec/containers/0/env/-
  value:
    name: VLLM_FUSED_MOE_CHUNK_SIZE
    value: "1024"
- op: add
  path: /spec/leaderWorkerTemplate/workerTemplate/spec/containers/0/env/-
  value:
    name: VLLM_ALL2ALL_BACKEND
    value: deepep_low_latency
- op: add
  path: /spec/leaderWorkerTemplate/workerTemplate/spec/containers/0/ports
  value:
    - containerPort: 8200
      name: metrics
      protocol: TCP
- op: add
  path: /spec/leaderWorkerTemplate/workerTemplate/spec/containers/0/readinessProbe
  value:
    httpGet:
      path: /health
      port: 8200
