apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - gatewayParameters.yaml

patches:
  - target:
      kind: HTTPRoute
    patch: |
      - op: add
        path: /spec/rules/0/timeouts
        value:
          backendRequest: 0s
          request: 0s
  - target:
      kind: Gateway
    patch: |
      - op: add
        path: /spec/infrastructure
        value:
          parametersRef:
            name: release-name-inference-gateway
            group: gateway.kgateway.dev
            kind: GatewayParameters
  - target:
      kind: Gateway
    patch: |-
      - op: add
        path: /spec/gatewayClassName
        value: kgateway
labels:
  - pairs:
      app.kubernetes.io/instance: wide-ep
      app.kubernetes.io/gateway: wide-ep-inference-gateway
      app.kubernetes.io/component: inference-gateway
