---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: v0.2.0
    helm.sh/chart: llm-d-modelservice-v0.2.11
  name: ms-pd-llm-d-modelservice-prefill
spec:
  replicas: 4
  selector:
    matchLabels:
      llm-d.ai/inferenceServing: "true"
      llm-d.ai/model: ms-pd-llm-d-modelservice
      llm-d.ai/role: prefill
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        llm-d.ai/inferenceServing: "true"
        llm-d.ai/model: ms-pd-llm-d-modelservice
        llm-d.ai/role: prefill
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        args:
        - |
          source /usr/local/gib/scripts/set_nccl_env.sh
          export LD_LIBRARY_PATH=/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}
          vllm serve RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic \
            --port 8000 \
            --served-model-name "RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic" \
            --block-size 128 \
            --kv-transfer-config '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}' \
            --disable-log-requests \
            --disable-uvicorn-access-log \
            --max-model-len 32000
      # - args:
      #   - google/gemma-3-27b-it # RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic
      #   - --port
      #   - "8000"
      #   - --served-model-name
      #   - google/gemma-3-27b-it
      #   - --block-size
      #   - "128"
      #   - --kv-transfer-config
      #   - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
      #   - --disable-uvicorn-access-log
      #   - --max-model-len
      #   - "32000"
      #   command:
      #   - vllm
      #   - serve
        env:
        - name: VLLM_NIXL_SIDE_CHANNEL_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: VLLM_LOGGING_LEVEL
          value: DEBUG
        - name: NCCL_TELEMETRY_MODE
          value: "0"
        - name: DP_SIZE
          value: "1"
        - name: TP_SIZE
          value: "1"
        - name: HF_HOME
          value: /model-cache
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              key: HF_TOKEN
              name: llm-d-hf-token
        image: ghcr.io/llm-d/llm-d-cuda:v0.3.0
        imagePullPolicy: IfNotPresent
        name: vllm
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        ports:
        - containerPort: 8000
          name: metrics
          protocol: TCP
        resources:
          claims:
            - name: gpu1
          limits:
            cpu: "8"
            memory: 640Gi
            # nvidia.com/gpu: "1"
          requests:
            cpu: "8"
            memory: 640Gi
            # nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /.config
          name: metrics-volume
        - mountPath: /dev/shm
          name: shm
        - mountPath: /.cache
          name: torch-compile-cache
        - mountPath: /model-cache
          name: model-storage
        - name: gib
          mountPath: /usr/local/gib
      resourceClaims:
        - name: gpu1
          resourceClaimTemplateName: 1-gpu-nic-aligned
      tolerations:
            - key: "nvidia.com/gpu"
              operator: "Equal"
              value: "present"
              effect: "NoSchedule"
      volumes:
      - emptyDir: {}
        name: metrics-volume
      - emptyDir:
          medium: Memory
          sizeLimit: 16Gi
        name: shm
      - emptyDir: {}
        name: torch-compile-cache
      - emptyDir:
          sizeLimit: 100Gi
        name: model-storage
      - name: gib
        hostPath:
          path: /home/kubernetes/bin/gib
