apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"vllm-baseline"},"name":"vllm-baseline","namespace":"glm-bench"},"spec":{"ports":[{"name":"http","port":8000,"targetPort":8000}],"selector":{"app":"vllm-baseline"}}}
    creationTimestamp: "2026-07-30T17:24:42Z"
    labels:
      app: vllm-baseline
    name: vllm-baseline
    namespace: glm-bench
    resourceVersion: "1785432282312383011"
    uid: 62ef803a-41f2-46f2-b6fb-a565b52dd128
  spec:
    clusterIP: 34.118.229.246
    clusterIPs:
    - 34.118.229.246
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: vllm-baseline
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: optimized-baseline
      meta.helm.sh/release-namespace: glm-bench
    creationTimestamp: "2026-07-30T17:24:45Z"
    labels:
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: optimized-baseline-epp
      app.kubernetes.io/version: v0.9.0
    name: optimized-baseline-epp
    namespace: glm-bench
    resourceVersion: "1785432285914719021"
    uid: 1209c3a3-87fb-4152-a213-b6ca0bc3bf23
  spec:
    clusterIP: 34.118.230.1
    clusterIPs:
    - 34.118.230.1
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: grpc-ext-proc
      port: 9002
      protocol: TCP
      targetPort: 9002
    - name: http-metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8081
    selector:
      llm-d-router-gateway: optimized-baseline-epp
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
